Add use_gpu for PureSVD
MobileTeleSystems/RecTools pull request #229
Opened 2024-12-11 04:42 UTC by chezou

## Description

Introduce `use_gpu` for PureSVD.

My microbenchmark code shows 8 times faster than CPU with Movielens 1M dataset.

```py
>>> import timeit
>>> with open("scripts/benchmark.py", "r") as f:
...     code = f.read()
...
>>> print(code)
import pandas as pd

from rectools import Columns
from rectools.dataset import Dataset
from rectools.models.pure_svd import PureSVDModel

ratings = pd.read_csv(
    "ml-1m/ratings.dat",
    sep="::",
    engine="python",  # Because of 2-chars separators
    header=None,
    names=[Columns.User, Columns.Item, Columns.Weight, Columns.Datetime],
)

# Create dataset
dataset = Dataset.construct(ratings)

model = PureSVDModel(factors=100, use_gpu={})
>>> timeit.timeit("model.fit(dataset)", setup=code.format(False), number=10)
42.881751499007805
>>> timeit.timeit("model.fit(dataset)", setup=code.format(True), number=10)
5.059483032004209
```

Environment information:

```sh
➜  RecTools git:(svd-gpu) ✗ poetry run python -c  "import cupy; cupy.show_config(_full=True)"
OS                           : Linux-5.15.167.4-microsoft-standard-WSL2-x86_64-with-glibc2.39
Python Version               : 3.12.3
CuPy Version                 : 13.3.0
CuPy Platform                : NVIDIA CUDA
NumPy Version                : 1.26.4
SciPy Version                : 1.12.0
Cython Build Version         : 0.29.36
Cython Runtime Version       : None
CUDA Root                    : /usr/local/cuda
nvcc PATH                    : /usr/local/cuda/bin/nvcc
CUDA Build Version           : 12060
CUDA Driver Version          : 12060
CUDA Runtime Version         : 12060 (linked to CuPy) / 12060 (locally installed)
CUDA Extra Include Dirs      : []
cuBLAS Version               : 120604
cuFFT Version                : 11300
cuRAND Version               : 10307
cuSOLVER Version             : (11, 7, 1)
cuSPARSE Version             : 12504
NVRTC Version                : (12, 6)
Thrust Version               : 200600
CUB Build Version            : 200600
Jitify Build Version         : <unknown>
cuDNN Build Version          : None
cuDNN Version                : None
NCCL Build Version           : None
NCCL Runtime Version         : None
cuTENSOR Version             : None
cuSPARSELt Build Version     : None
Device 0 Name                : NVIDIA GeForce RTX 3060 Ti
Device 0 Compute Capability  : 86
Device 0 PCI Bus ID          : 0000:09:00.0
```

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Optimization

## How Has This Been Tested?
Before submitting a PR, please check yourself against the following list. It would save us quite a lot of time.
- Have you read the contribution guide?
- Have you updated the relevant docstrings? We're using Numpy format, please double-check yourself
- Does your change require any new tests?
- Have you updated the changelog file?

2025-01-16 12:45 UTC, feldlime reviewed
Thanks for the PR, it looks super cool!

2025-01-16 12:45 UTC, feldlime commented on CHANGELOG.md
> +- Add `use_gpu` for PureSVD ([#229](https://github.com/MobileTeleSystems/RecTools/pull/229))
Please pull the fresh version of `main` before merging

2025-01-16 12:45 UTC, feldlime commented on pyproject.toml
> +    "cupy-cuda12x",
Let's probably make a shorter `cupy` extra?
@blondered fyi

2025-01-16 12:45 UTC, feldlime commented on rectools/models/pure_svd.py
> +            if not HAS_CUDA:
I think it's better to use `cp.cuda.runtime.getDeviceCount() == 0` instead:
1. To achieve full compatibility and do not depend on implicit
2. There is an issue that on some machines with GPU and Cuda available, and e.g. torch is working, `HAS_CUDA` is still `False`

2025-01-16 12:45 UTC, feldlime commented on rectools/models/pure_svd.py
> +        self.use_gpu = use_gpu
We need to preserve the initial value for config. You can use the idea from [here](https://github.com/MobileTeleSystems/RecTools/blob/main/rectools/models/lightfm.py#L152)

2025-01-16 15:45 UTC, chezou commented on rectools/models/pure_svd.py
> +            if not HAS_CUDA:
Okay, I'll use `cp.cuda.runtime.getDeviceCount() == 0` instead.

I aware that `recommend_use_gpu_ranking` depends on `HAS_CUDA`, so we may have room for consistency.
https://github.com/MobileTeleSystems/RecTools/pull/229/files#diff-95c3d16fac303204b014a3e5359eb37c595633c1950b7e5f31738a819717dbe0R81

2025-01-16 15:52 UTC, chezou commented on rectools/models/pure_svd.py
> +        self.use_gpu = use_gpu
Fixed 6c060fbf6f266e9c7347c28431d7c3ae144e6ffa

2025-01-16 15:52 UTC, chezou commented on rectools/models/pure_svd.py
> +            if not HAS_CUDA:
Fixed 6c060fbf6f266e9c7347c28431d7c3ae144e6ffa

2025-01-16 15:53 UTC, chezou commented on CHANGELOG.md
> +- Add `use_gpu` for PureSVD ([#229](https://github.com/MobileTeleSystems/RecTools/pull/229))
Updated :)

2025-01-16 20:08 UTC, feldlime commented on rectools/models/pure_svd.py
> +            if not HAS_CUDA:
`recommend_use_gpu_ranking` uses the `recommend` method from `implicit`, if `implicit` doesn't see Cuda, it won't work on GPU, and here it may still work if `cupy` sees Cuda (also vice versa - if implicit sees cuda and cupy doesn't)

2025-01-16 21:16 UTC, chezou commented on pyproject.toml
> +    "cupy-cuda12x",
Yes, that should be covered by `extras = ["cupy"]`, isn't it?

```
cupy-cuda12x = {version = "^13.3.0", python = "<3.13", extras = ["cupy"], optional = true}cupy-cuda12x = {version = "^13.3.0", python = "<3.13", extras = ["cupy"], optional = true}
```

I added cupy extras by using `poetry add` with `--extras` option.
https://python-poetry.org/docs/cli/#options-5

2025-01-16 21:31 UTC, chezou commented
Python 3.9 CI fails because of codecov issue. Test is passed.
> error - 2025-01-16 17:47:40,999 -- Report creating failed: {"message":"Token required because branch is protected"}

2025-01-23 19:15 UTC, chezou commented
@feldlime I addressed all the comments you made. PTAL

2025-02-01 21:43 UTC, feldlime requested changes
@chezou Sorry for the delay, I added one more small (but critical) comment, and you need to update the changelog one more time (since this change not in the 0.10.0 release), then we're ready to merge

2025-02-01 21:43 UTC, feldlime commented on rectools/models/pure_svd.py
> +        self._use_gpu = use_gpu  # for making a config
We need to do this before changing the given value of `use_gpu` since we want to keep in config the values that were used by user while creating the model

2025-02-01 23:21 UTC, chezou commented on rectools/models/pure_svd.py
> +        self._use_gpu = use_gpu  # for making a config
Fixed b92ed6b

2025-02-01 23:28 UTC, chezou commented
@feldlime Updated the changelog, as well as the order of assignment.

2025-02-02 09:19 UTC, feldlime approved these changes

2025-02-02 09:20 UTC, merged