Feature/recommend internal ids
MobileTeleSystems/RecTools pull request #70
Opened 2023-11-26 16:03 UTC by feldlime

- Added ability to pass internal ids to `recommend` and `recommend_to_items` methods and get internal ids back

2023-11-27 11:00 UTC, blondered requested changes

2023-11-27 11:00 UTC, blondered commented on rectools/models/base.py
> +            When ``True`` user and item ids in returning recommendations dataset will be external.
```suggestion
            When ``True`` user and item ids in returning recommendations table will be external.
```

2023-11-27 11:00 UTC, blondered commented on rectools/models/base.py
> +            1st column contains external (internal if `return_external_ids` is ``False``) user ids,
```suggestion
            1st column contains user ids
```

2023-11-27 11:00 UTC, blondered commented on rectools/models/base.py
> +            2nd - external (internal if `return_external_ids` is ``False``) ids of recommended items
```suggestion
            2nd - ids of recommended items sorted by relevance for each user
```

2023-11-27 11:00 UTC, blondered commented on rectools/models/base.py
> +            When ``True`` item ids in returning recommendations dataset will be external.
```suggestion
            When ``True`` item ids in returning recommendations table will be external.
```

2023-11-27 11:00 UTC, blondered commented on rectools/models/base.py
> +                  sorted for each target item by relevance,
```suggestion
            2nd - ids of recommended items sorted by relevance for each target item
```

2023-11-27 11:00 UTC, blondered commented on rectools/models/base.py
> +            Recommendations table with columns `Columns.TargetItem`, `Columns.Item`, `Columns.Score`[, `Columns.Rank`].
```suggestion
            Recommendations table with columns `Columns.TargetItem`, `Columns.Item`, `Columns.Score`[, `Columns.Rank`]. External item ids are used by default. For internal ids set `return_external_ids` to ``False``
```

2023-11-27 11:00 UTC, blondered commented on rectools/models/base.py
> +            1st column contains external (internal if `return_external_ids` is ``False``) target item ids,
```suggestion
            1st column contains target item ids,
```

2023-11-27 11:00 UTC, blondered commented on rectools/models/base.py
> +            Recommendations table with columns `Columns.User`, `Columns.Item`, `Columns.Score`[, `Columns.Rank`]\.
```suggestion
            Recommendations table with columns `Columns.User`, `Columns.Item`, `Columns.Score`[, `Columns.Rank`]\. External user and item ids are used by default. For internal ids set `return_external_ids` to ``False``
```

2023-11-27 11:04 UTC, feldlime commented on rectools/models/base.py
> +            When ``True`` item ids in returning recommendations dataset will be external.
fixed

2023-11-27 11:29 UTC, feldlime commented on rectools/models/base.py
> +            1st column contains external (internal if `return_external_ids` is ``False``) user ids,
fixed

2023-11-27 11:29 UTC, feldlime commented on rectools/models/base.py
> +            2nd - external (internal if `return_external_ids` is ``False``) ids of recommended items
fixed

2023-11-27 11:29 UTC, feldlime commented on rectools/models/base.py
> +            1st column contains external (internal if `return_external_ids` is ``False``) target item ids,
fixed

2023-11-27 11:31 UTC, feldlime commented on rectools/models/base.py
> +                  sorted for each target item by relevance,
fixed

2023-11-27 11:40 UTC, feldlime commented on rectools/models/base.py
> +            Recommendations table with columns `Columns.User`, `Columns.Item`, `Columns.Score`[, `Columns.Rank`]\.
fixed

2023-11-28 09:36 UTC, feldlime commented on CHANGELOG.md
> +## Unreleased
fixed

2023-11-28 09:57 UTC, blondered approved these changes

2023-11-28 10:07 UTC, merged